### ISSUE TITLE
producing stability measures from pdb structure?

### ISSUE THREAD

**Issue by avilella** [lehner-lab/doubledeepms#2]
Hi @andrefaure , how are you? Long time!

I have a project where I calculate the predicted in silico stability of the folded proteins produced by Alphafold2, and try to see if the calculated stability measure correlates with experimental data for these proteins.

I am interested in methods for this: could I use doubledeepms to give me a stability score for a pdb input file? I see there is a "comparison to foldx" section in the README file.

Thanks in advance.

**Comment by andrefaure** [comment]
Hi @avilella great to hear from you!

This repo is very much focussed on the analysis of DMS data. We compared the folding energies inferred from this experimental data to those computationally predicted by foldx in that section you refer to.

If you are interested in stability metrics from pdb I would use that tool (and others) directly:
https://foldxsuite.crg.eu/

Hope this helps!
